"""Your migration message

Revision ID: aa52aae647d8
Revises: 46b52ee47fac
Create Date: 2025-04-29 12:02:15.472027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aa52aae647d8'
down_revision: Union[str, None] = '46b52ee47fac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'add_to_cart')
    op.drop_column('books', 'is_available_for_purchase')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('is_available_for_purchase', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('add_to_cart', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
